### ISSUE TITLE
Add possibility to define own template generation file

### ISSUE THREAD

**Issue by ollifer** [Distelli/graphql-apigen#23]
As I see now we can't change structure of template file that generates java classes. 
It would better to define own template that does fit into particular requirements. 
For example, we don't need any model interfaces, builders, resolvers, etc, we need only java pojo with getter/setters.

**Comment by brimworks** [comment]
You can already do this by placing a file in the root of your maven project named graphql-apigen.stg, you can take a look at apigen/src/main/resources/graphql-apigen.stg for an example of the format of this file.

Note that I have intentionally not documented this since I'm not certain that I really enjoy the string template syntax and others have also had troubles with it.

If you can give this a try and give me feedback that would be great. If you have alternative template suggestions, I'm open to giving them a try as an alternative.

Thanks,
-Brian

**Comment by rtti** [comment]
Thanks for the reply. Yeah, I haven't found this,but now have! 
I played with stg template and there is some question I want to ask - 
If we have such structure `type Human implements Character` should our generated classes implement Character interface? And how can we get such info from model?

**Comment by brimworks** [comment]
Unfortunately, the STModel.java currently doesn't expose that information :(. Feel free to add a method to STModel to expose that information and send a PR (pull request).

Thanks,
-Brian

**Comment by amareen1988** [comment]
I just cloned the graphql-apigen project and was able to pull this off. I will be creating a PR soon.

**Comment by kito99** [comment]
@brimworks shouldn't this be closed since it was merged?

**Comment by brimworks** [comment]
Thanks! Forgot about this one too.
