### ISSUE TITLE
IDL shouldn't require java packagenames - specify option in mojo for a default?

### ISSUE THREAD

**Issue by ryangardner** [Distelli/graphql-apigen#5]
It'd be nice if the IDL didn't need to have anything about the java package names in it. 

If the mojo were able to take a parameter for the default packagename to generate things into, you could strip that out of the IDL (Unless something needed to override the package for one of the types?)

**Comment by brimworks** [comment]
This is a great idea!

**Comment by brimworks** [comment]
Note that one problem with this approach (that I'm just now realizing) is that we don't capture information about the java package names after the code is generated. This is only problematic if you have a graphql schema depend on another graphql schema that was generated by a different maven project. One way to fix this is to generate output graphql files with this extra annotation as an annotation, but that will be a fair bit of work since it requires writing a graphql serializer.

...so I'll leave this as is and just add a note in the README.
